repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.0.1
  hooks:
  - id: reorder-python-imports
    language_version: python3.6
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: end-of-file-fixer
  - id: check-json
  - id: check-yaml
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: requirements-txt-fixer
  - id: flake8
